drop test tables on cleanup
WordPress/phpunit-test-runner pull request #138
Opened 2021-01-12 18:08 UTC by mrxkon

Fixes #110

Adds functionality to remove test tables from the database during cleanup.

2021-01-15 13:00 UTC, getsource commented
Thanks much for the PR!

I took a look, and I think this wouldn't work as expected when the database is only accessible from the test environment (when the test environment is not the same as the prepare one).

You can see an example in [cleanup.php](https://github.com/WordPress/phpunit-test-runner/blob/master/cleanup.php#L28) of how it's done for removing files.

Maybe something similar to that would work?

2021-01-15 13:45 UTC, mrxkon commented
Hey @getsource , sure yeah, that's why I mentioned it in the issue comment since I'm only working locally :D .

If `mysql` is in general accessible everywhere ( since we're either way using shell_exec and other direct cli access as well ) we can go for oneliners like `mysql -u $user -p$pass $db -e "drop table if exists $table;"` and just iterate with that as a direct shell (and overssh) command.

This would work both locally and remotely I suppose.

2021-01-15 14:15 UTC, getsource commented
Ah, sorry, I missed the issue comment!

Yes, I think something like that makes sense. The only thing that comes to mind is that I think that would result in the MySQL password being stored in logs.

2024-01-23 01:54 UTC, grooverdan approved these changes
could get into issues if ever `$prefix` needed SQL escaping, but seems unlikely.

`mysql` as a command generally got phased out of MariaDB-11.0+ an use `mariadb` instead.

MYSQL_PWD as an env variable for password still generally works, though could create a configuration file with `[mysql]\npassword=....` and pass that to the command.

2025-05-07 18:52 UTC, kittenkamala commented
This might be mergable but I think it needs a rebase and to be tested again.

2025-08-14 06:19 UTC, Crixu reviewed
All looks good and straight forwards. As @kittenkamala mentioned we need some testers to run this to see if it still works

2026-08-12 22:51 UTC, kittenkamala requested changes
Thank you! This is failing cs tests, citing accessing the db directly. Should be updated to use $wpdb

2026-08-26 18:53 UTC, kittenkamala commented
@ekamran is taking over work on this. Can't assign to him due to not being a WP.org GitHub org member

2026-09-09 18:42 UTC, kittenkamala commented
Moved to https://github.com/WordPress/phpunit-test-runner/pull/337 - closing

2026-09-09 18:42 UTC, closed without merging