Multi PHP
WordPress/phpunit-test-runner pull request #212
Opened 2024-03-16 18:02 UTC by javiercasares

This is the first version that allows multi-PHP versions so we can test 2 or 3 at the same time.

There is also a PR ready to get the information into the test-reporter

2024-03-16 18:02 UTC, javiercasares commented
FYI: https://github.com/WordPress/phpunit-test-reporter/pull/109

2024-03-17 14:21 UTC, javiercasares commented
The code is not very beauty, but it should work...

2024-06-13 12:19 UTC, pfefferle commented on .env.default
> +# (Optionally) array of versions (like: 8.0+/bin/php8.0,8.1+/bin/php8.1)
```suggestion
# (Optionally) array of versions (like: 8.0=/bin/php8.0;8.1=/bin/php8.1)
```

Maybe we should use the Link header syntax instead `8.0=/bin/php8.0;8.1=/bin/php8.1` because the `+` is also used by semantic versioning and might be used in the executable string.

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Link
https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions

2024-06-13 12:19 UTC, pfefferle commented on docs/1-setup.md
> +If you are using Debian / Ubuntu, install or update NodeJS 18 with this command:
```suggestion
If you are using Debian / Ubuntu, install or update NodeJS 20 with this command:
```

2024-06-13 12:19 UTC, pfefferle commented on docs/1-setup.md
> +# (Optionally) array of versions (like: 8.0+/bin/php8.0,8.1+/bin/php8.1)
```suggestion
# (Optionally) array of versions (like: 8.0=/bin/php8.0;8.1=/bin/php8.1)
```

2024-06-13 12:19 UTC, pfefferle commented on docs/1-setup.md
> +`8.0+/bin/php8.0,8.1+/bin/php8.1`
```suggestion
`8.0=/bin/php8.0;8.1=/bin/php8.1`
```

2024-06-13 12:19 UTC, pfefferle commented on docs/1-setup.md
> +export WPT_PHP_EXECUTABLE_MULTI=7.4+/bin/php7.4,8.3+/bin/php8.3
```suggestion
export WPT_PHP_EXECUTABLE_MULTI=7.4=/bin/php7.4;8.3=/bin/php8.3
```

2024-06-13 12:19 UTC, pfefferle commented on functions.php
> +		/* THIS IS A TEMPORARY (or not) COMMENTED CODE
???

2024-06-13 12:19 UTC, pfefferle commented on prepare.php
> +		$php_multi_v = explode( '+', $php_multi_version );
```suggestion
		$php_multi_v = explode( '=', $php_multi_version );
```

2024-06-13 12:19 UTC, pfefferle commented on prepare.php
> +	$php_multi_versions = explode( ',', $WPT_PHP_EXECUTABLE_MULTI );
```suggestion
	$php_multi_versions = explode( ';', $WPT_PHP_EXECUTABLE_MULTI );
```

2024-06-13 12:19 UTC, pfefferle commented on report.php
> +$WPT_PHP_EXECUTABLE_MULTI = trim( getenv( 'WPT_PHP_EXECUTABLE_MULTI' ) ) ? : '';
maybe align it by the `=`

2024-06-13 12:19 UTC, pfefferle commented on prepare.php
> +	'label'					 => '{$WPT_LABEL}',
there seems to be something broken with the indents?!

2024-09-28 17:35 UTC, javiercasares commented on functions.php
> +		/* THIS IS A TEMPORARY (or not) COMMENTED CODE
won't be there in next commits ;)

2024-09-29 07:30 UTC, javiercasares commented
I applied the suggestion @pfefferle did on WordCamp Europe, and reduce a lot of duplicated code that we couldn't do at the Cloudfest Hackathon, mostly on the parts when testing multiple PHP versions.

I did some improvements on the documentation, with some scripts so the software (from the main branch) is updated and maintained automatically.

I've been doing some tests in my local machine, and on my production server (where I was doing the former tests) and looks like everything is working.

On my side, I think everything is in order, and we can approve this and put it available for everyone.

2024-10-02 12:10 UTC, benniledl commented
### Running tests in parallel?
Running the PHPUnit test suite across 7 different PHP versions is taking a long time in my environment. Is there a way to run the tests in parallel to speed things up?

### Preparing a new environment for every version necessary?
Also, is it necessary to create a completely new environment for each PHP version? So far, I've been running the prepare.php file for the first PHP version, then report.php then using a script to search and replace the PHP version in the configuration files before rerunning the tests and reporting again. This approach seemed to work.

### Copying the environment + Running in parallel
I could see that using the same environment for multiple php versions in parallel could cause problems, is it maybe possible to just copy one environment to a different directory and then replace the php version in the config? Since preparing an environment also takes a long time for me.

2025-03-13 09:45 UTC, WesRapyd commented
What is the status of this pull ???

2025-05-08 06:57 UTC, Crixu approved these changes

2025-08-07 21:37 UTC, kittenkamala approved these changes

2025-08-07 21:37 UTC, kittenkamala commented
I would like to have someone with access to hosting envs test this before we merge if possible

2025-08-13 13:28 UTC, desrosj commented
I'm going to put some time towards getting this tested and merged over the course of the next few weeks.

At Bluehost, we currently have a fork that we used to make changes directly and get our tests back up and running. However, it's a bit of a pain to maintain those small differences while keeping the fork in sync with changes here. Some of the changes actually unintentionally accomplish multi-php but just through the GitHub Action.

This PR is quite a bear, though. I am going to try and pull all of the unrelated documentation changes into a separate pull request, and all other unrelated functional changes into another in order to make this more focused.

2025-08-13 19:51 UTC, kittenkamala commented
> I'm going to put some time towards getting this tested and merged over the course of the next few weeks.
> 
> At Bluehost, we currently have a fork that we used to make changes directly and get our tests back up and running. However, it's a bit of a pain to maintain those small differences while keeping the fork in sync with changes here. Some of the changes actually unintentionally accomplish multi-php but just through the GitHub Action.
> 
> This PR is quite a bear, though. I am going to try and pull all of the unrelated documentation changes into a separate pull request, and all other unrelated functional changes into another in order to make this more focused.

Thank you so much, @desrosj !!

2025-08-26 07:11 UTC, desrosj requested changes
I've been extracting out some of the changes in this pull request that are unrelated to achieving multi PHP/multi environment/multi commit testing and tracking.

There are some merge conflicts that need to be resolved after (and if) #262, #256, and #255 are merged, but for now I've left some feedback on the parts specific to the goals of the PR.

2025-08-26 07:11 UTC, desrosj commented on docs/1-setup.md
> +Use as much versions as you want, but it will take more time. The idea is to put all the versions offered to users.
```suggestion
Use as many versions as you'd like, but keep in mind that it will take more time. Ideally all versions offered to users are tested.
```

2025-08-26 07:11 UTC, desrosj commented on report.php
> +	$WPT_TEST_DIR_MULTI = $WPT_TEST_DIR . '-' . crc32( $php_multi['version'] );
Is there a reason why the version needs to be obfuscated? `$php_multi['version]` should only be set to `8.1`, `8.0`, etc. Including the version in the directory name in plain text could be very helpful for debugging purposes.

What about something like this instead?
```suggestion
	$WPT_PREPARE_DIR_MULTI = $WPT_PREPARE_DIR . '-' . str_replace( '.', '-', $php_multi['version'] );
	$WPT_TEST_DIR_MULTI = $WPT_TEST_DIR . '-' . str_replace( '.', '-', $php_multi['version'] );
```

It occurs multiple times, so I think a helper function in `functions.php` may be good.
```
function directory_name_from_php_version( $version ) {
	return str_replace( '.', '-', $version] );
}
```

2025-08-26 07:11 UTC, desrosj commented on .env.default
> +
Is a new environment variable necessary? Could `WPT_PHP_EXECUTABLE` be made to accept single or array values instead?

The default can still remain as `php`, and the code below responsible for parsing the value can check for the presence of `=` and/or `;` characters to process as an array.

2025-08-26 07:11 UTC, desrosj commented on cleanup.php
> +$WPT_PREPARE_DIR          = trim( getenv( 'WPT_PREPARE_DIR' ) ) ? : '/tmp/wp-test-runner';
Applying these new, default values has been extracted out into #262.

2025-08-26 07:11 UTC, desrosj commented on commits.json
> +{
It's not quite clear what each of these represent based on their names. Have the `executed_commits` been successfully tested and reported? If the runner fails to be configured and run the tests is it included in that list?

Are `pending_commits` in a queue to be tested? Something else? Are `testing_commit` being tested right now? Will this never be more than one?

Also, not sure if this file is here for testing purposes, but it should probably be added to the `.gitignore` file.

2025-08-26 07:11 UTC, desrosj commented on prepare.php
> +		if ( file_exists( $commits_file ) ) {
If the file does not exist and `$WPT_COMMITS`, the runner should copy the example file to ensure the same hashes are not retested.

2025-08-26 07:11 UTC, desrosj commented on .env.default
> +# 1 = all
All is a bit misleading here because the [API caps the results per page at 100](https://docs.github.com/en/rest/commits/commits#list-commits). The default is 30.

I would change this to an on or off value. If it's on, the runner will query for the last 30 commits and add them to the queue if they have not yet been tested. If it's off, then only the most recent commit when the runner starts should be tested.

Regardless of this value, though, I think that the `commits.json` file should still be used to track what has been tested. This will help avoid re-running the suite for a commit that has already been tested and reported.

2026-07-29 18:45 UTC, kittenkamala commented
What needs to be done for this moving forward:

- Rebase and merge conflicts resolved. Retaining the changes made in https://github.com/WordPress/phpunit-test-runner/pull/262/changes, https://github.com/WordPress/phpunit-test-runner/pull/256/changes, and https://github.com/WordPress/phpunit-test-runner/pull/255/changes 

- Implement the changes @desrosj suggested above

- This needs testing on hosting infra or on LAMP/LEMP containers

2026-08-12 19:07 UTC, kittenkamala commented
[github.com/dilipom13](https://github.com/dilipom13) is working on this starting with resolving those merge conflicts

2026-08-14 18:35 UTC, dilipom13 commented
Hello @kittenkamala 

I don’t have write access to this fork (`javiercasares:multi-php`), so I opened a new PR with the updated branch:
https://github.com/WordPress/phpunit-test-runner/pull/333
That PR keeps the already-merged pieces from #262, #255, and #254, and implements the review feedback from @desrosj:
- Directory names use the PHP version in plain text (e.g. `-8-1`) instead of `crc32`
- No new `WPT_PHP_EXECUTABLE_MULTI` variable — `WPT_PHP_EXECUTABLE` now accepts a single binary or `version=path;version=path`
- `commits.json` is gitignored, created from an example file if missing, and used to skip already-tested SHAs
- `WPT_COMMITS` is on/off (last 30 commits vs latest only)
Local checks that passed: PHP syntax, PHPCS, helper logic, and live GitHub commit fetching. A full prepare/test/report run on hosting or a LAMP/LEMP container is still needed.

Happy to continue from #333 if that’s the preferred path.

If you have any other suggestions for me, please let me know.

2026-08-26 02:26 UTC, kittenkamala commented
Closing, updated PR #333

2026-08-26 02:26 UTC, closed without merging